name: CI - Shopify Theme Check

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  theme-check:
    name: Shopify Theme Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Theme Check
        run: npm run theme-check
